### PR TITLE
feat: laravel 8/9/10 support

### LINKED ISSUE #8: Laravel 8 Support
I created a PR for this feature in Laravel version 8.
I haven't integrated it in this package because I am quite busy but if I got the time I will do it.
For the meantime if you want, you can copy this code and implement it first in your project.

https://github.com/laravel/framework/pull/37456

### LINKED ISSUE #12: [Support] Laravel 9
Hey,

I was wondering if this trait support Laravel 9 ?

### PR DESCRIPTION
**Pull request by audunru**
BREAKING CHANGE: Support for Laravel 8/9/10. Drops support for Laravel 5/6/7.

Based on [ajcastro's PR to laravel/framework](https://github.com/laravel/framework/pull/37456) which was not accepted, sadly.

In this PR we override the `newBelongsToMany()` method of Laravel's `HasRelationships` trait and replace the BelongsToMany class with our own version with support for eager loading pivot relations.

Overriding `BelongsToMany's get()` method is not exactly the cleanest solution, but it allows us to tack on support only for BelongsToMany relationships and gives access to the `$accessor` property in a clean fashion. In the previous version, some code was dedicated to discovering the relationship model's `$accessor` value from the query builder. IMO this is easier to understand, so I understand the original author's decision to go that way. The downside is some duplication of framework code in the overriden `get()` method now that we have to do this outside of the framework itself.

I suggest that in the future, in order to support newer versions of Laravel, backwards compatibility is dropped in favor of a potentially cleaner solution if we find one.

Thank you for the actual work on this @ajcastro :-)

Minimum PHP version bumped to 7.3 to match Laravel 8's minimum. orchestra/testbench bumped to v6 to match Laravel 8.

Tested with a Laravel 10 application on PHP 8.2.

Close #8 
Close #12

### CODE REVIEW

**Comment by ricardoaranha96** [comment]
@audunru would you consider publish it as a new package if the PR doesn't get approved? There's been a while since the last commit done by @ajcastro  For now, I coppied your code to my project in order to use it. You saved me.

**Comment by audunru** [comment]
That's a possibility. I'm currently referencing my forked repo in my composer.json just to get it working, but a published package would be preferrable. Hopefully we can get it merged.

**Comment by audunru** [comment]
@ricardoaranha96 Will publish this as a new package

**Comment by ricardoaranha96** [comment]
@audunru Thank you very much

**Comment by ryanmortier** [comment]
@audunru Thank you for maintaining your fork. It's working great for me.

**Pull request closed without merging**
